# shellcheck shell=bash
# Gum CLI theme (Phosphor Green - Old CRT aesthetic)
export GUM_FILTER_INDICATOR_FOREGROUND="46"
export GUM_FILTER_PROMPT_FOREGROUND="71"
export GUM_FILTER_PLACEHOLDER_FOREGROUND="65"
export GUM_FILTER_HEADER_FOREGROUND="214"
export GUM_FILTER_MATCH_FOREGROUND="46"

export GUM_CHOOSE_CURSOR_FOREGROUND="46"
export GUM_CHOOSE_HEADER_FOREGROUND="214"
export GUM_CHOOSE_SELECTED_FOREGROUND="16"
export GUM_CHOOSE_SELECTED_BACKGROUND="46"

export GUM_INPUT_CURSOR_FOREGROUND="46"
export GUM_INPUT_PROMPT_FOREGROUND="71"
export GUM_INPUT_HEADER_FOREGROUND="214"

export GUM_CONFIRM_SELECTED_FOREGROUND="16"
export GUM_CONFIRM_SELECTED_BACKGROUND="46"
